In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances

bag_of_sentences = [
"list of fruits",
"array of vegetables",
"to check if it is a fruit",
"check that the file opens",
"add two numbers",
"guess a number",
"enter a positive number less than 1000",
"enter your name",
"variable to search for an event on a selected date",
"different range of incomes"
]



In [2]:
#def word_extraction(bag_of_sentences):
#    ignore = ['a', "the", "is","to","for","on","an"]
#    words = re.sub("[^\w]", " ",  bag_of_sentences).split()
#    cleaned_words = [w.lower() for w in words if w not in ignore]
#    return cleaned_words
#print(cleaned_words)
def extract_words(sentence):
    ignore_words = ["a", "the", "is","to","for","on","an","that","of"]
    words = re.sub("[^\w]", " ",  sentence).split() #nltk.word_tokenize(sentence)
    words_cleaned = [w.lower() for w in words if w not in ignore_words]
    return words_cleaned

In [3]:
def tokenize_sentences(bag_of_sentences):
    words = []
    for sentence in bag_of_sentences:
        w = extract_words(sentence)
        words.extend(w)
        
    words = sorted(list(set(words)))
    return words

In [4]:
import numpy as np
import re

def bagofwords(sentence, words):
    sentence_words = extract_words(sentence)
    # frequency word count
    bag = np.zeros(len(words))
    for sw in sentence_words:
        for i,word in enumerate(words):
            if word == sw: 
                bag[i] += 1
                
    return np.array(bag)

In [5]:
vocabulary = tokenize_sentences(bag_of_sentences)

In [6]:
vectorizer = CountVectorizer()
print( vectorizer.fit_transform(vocabulary).todense() )
vocabList = vectorizer.vocabulary_
print(vocabList)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0

In [7]:
vectorizer = CountVectorizer(analyzer = "word", tokenizer = None, preprocessor = None, stop_words = None, max_features = 5000) 
features = vectorizer.fit_transform(vocabulary).todense()
result_array = vectorizer.transform(["array of numbers"]).toarray()
print(vectorizer.transform(["array of numbers"]).toarray())

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]


In [14]:
i = 0
listofValues = []
variableName = ''
for output in result_array:
    while i < len(output):
        if output[i] == 1:
            for key,value in vocabList.items():
                if value == i:
                    variableName += key
#            listOfValues = [value  for (key, value) in vocabList.items() if key == i]
        i += 1
     
print(variableName)
#for value  in listOfValues:
#    print(value)  
        
    

arraynumbers
